import psycopg2 as pg
import os
import uuid
from rich.console import Console
from dotenv import load_dotenv

load_dotenv()

console = Console()

"""
    This file is used to fill the database with images
    The images are in the folder src/data
    The images are uploaded to the database in the table image

"""


database = "./src/data"

def upload_Image(path):

    conn = None

    try:

        conn = pg.connect(
            host=os.getenv("DB_HOST"),
            database=os.getenv("DB_NAME"),
            user=os.getenv("DB_USER"),
            password=os.getenv("DB_PASSWORD")
        )

        cur = conn.cursor()

        # insert in image table the path of the image and the id is a uuid() generated by postgres 
        # don't show this error "null value in column "id" of relation "image" violates not-null constraint"
        
        uuids = uuid.uuid4()
        uuids = str(uuids)
        cur.execute("INSERT INTO image (id,path) VALUES (%s,%s)", (uuids,path,))

        conn.commit()

    except (Exception, pg.DatabaseError) as error:  
        print(error)
    
    finally:
        if conn is not None:
            conn.close()


def upload_Images():

    for image in os.listdir(database):
        if image.endswith(".jpg"):
            upload_Image(os.path.join(database, image))


if __name__ == '__main__':
    upload_Images()
    console.print("[bold green]Data Uploaded[/bold green]")
